name: people_browser_app
description: A simple people browser app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true